### PR TITLE
Add 'mergeinfo' command & Update etc

### PR DESCRIPTION
**Pull request by pineoc**
## PR summary

- Added mergeinfo command
- Added travis cache config
- Update double qoute to single qoute

## mergeinfo

- `--show-revs` works (eligible, merged)
- `--xml` not working (svn not supported)

### CODE REVIEW

**Review by peteward44 — APPROVED** [review]

**Comment by peteward44** [comment]
Nice thanks 👍

**Comment by pineoc** [comment]
Thanks! @peteward44

I would like to contribute to your project as a maintainer.
I'll do my best!

**Comment by peteward44** [comment]
You are more than welcome! I can transfer the npm package over to you if you wish. What is your npmjs.com username?

**Comment by pineoc** [comment]
Oh, thanks for inviting me on your project!
my npmjs username same as github username. pineoc

**Pull request merged**
